### ISSUE TITLE
BadCard does not start

### ISSUE THREAD

**Issue by Herna4ndes** [VoidNoi/BadCard#11]
As we discussed previously. Version 1.6.3 does not start and stays in an infinite loop. Here is an example:
https://youtu.be/uhR6mxIiEaQ

**Comment by VoidNoi** [comment]
And this happens without m5launcher too right?

**Comment by Herna4ndes** [comment]
Yes. If I install directly via OTA, no. However, when restarting the cardputer, the installation disappears. the previous version was starting normally with m5launcher.

https://youtube.com/shorts/YJYtGyw8e-U

**Comment by Herna4ndes** [comment]
I managed to solve it. the problem was with my SD card
Sorry

**Comment by VoidNoi** [comment]
I was about to say that you probably had a corrupted bin or something. Next time if you have an error with a firmware try installing it through m5burner directly first and if you get a black screen do the steps I said here https://github.com/VoidNoi/BadCard/issues/10#issuecomment-2364550770 but flashing it from m5burner, not m5launcher
