### ISSUE TITLE
Mismatched scancodes for PT_BR keyboard layout

### ISSUE THREAD

**Issue by Herna4ndes** [VoidNoi/BadCard#9]
Hello everything is fine? I'm having problems with version 1.6.0. When I try to run the eBadCard script, I change the "/" to ";" and it ends up giving an error in the script. Could you help me please?

**Comment by VoidNoi** [comment]
I'm gonna need more information. What is the error? What script are you using? What do you mean by "changing the "/" to ";""

**Comment by Herna4ndes** [comment]
Right. Any script that I try to use on the PT_BR keyboard, BadCard is interpreting / as ;
an example: 
DELAY 500
GUI r
DELAY 500
STRING shutdown /s /f /t 0
ENTER

it interprets in command prompt or powershell:
DELAY 500
GUI r
DELAY 500
STRING shutdown ;s ;f ;t 0
ENTER


![CMD erro1](https://github.com/user-attachments/assets/f3254668-a5bd-470b-9c30-34c754e72c72)


"shutdown ;s ;f ;t 0
Usage: shutdown [/i | /l | /s | /sg | /r | /g | /a | /p | /h | /e | /o] [/hybrid] [/soft] [/fw] [/f] [/m \\computer][/t xxx][/d [p|u:]xx:yy [/c "comment"]]

Without args       Display help. This is the same as typing /?.
/?                 Display help. This is the same as not typing any option.
/i                 Display the graphical user interface (GUI).  
                   This must be the first option.
/l                 Log off. Cannot be used with /m or /d options.
/s                 Shutdown the computer.
/sg                Shutdown the computer. On the next start, if Automatic Restart Sign-On is enabled, log in automatically and display the last interactive user.
/r                 Shutdown and restart the computer.
/g                 Shutdown and restart the computer. After the restart, restart all registered applications.
/a                 Abort a system shutdown.
/p                 Turn off the local computer without any delay or warning.  
                   Can be used with /fw to clear pending updates to firmware.
/h                 Hibernate the local computer.
                   Can be used with the /f option.
/hybrid            Perform a shutdown and prepare for a fast startup.
                   Must be used with /s.
/fw                Combined with a shutdown option to ensure that the next startup goes to the firmware user interface.
/e                 Document the reason for an unexpected shutdown.
/o                 Go to the advanced boot options menu and restart the computer.  
                   Must be used with /r option.
/m \\computer      Specify the target computer.
/t xxx             Set the delay for shutdown to xxx seconds.
                   Valid range is 0-315360000 (10 years), with a default of 30.
                   If the timeout is greater than 0, the /f option is implied.
/c "comment"       Comment on the reason for the restart or shutdown.
                   Maximum of 512 characters allowed.
/f                 Force running applications to close without warning users.
                   The /f parameter is implied when a timeout greater than 0 is set.
/d [p|u:]xx:yy     Provide a reason for the restart or shutdown."

**Comment by Herna4ndes** [comment]
When I run the script in Bruce it runs normally but not in BadCard.

**Comment by VoidNoi** [comment]
That's very interesting because I believe bruce uses the same library as me but the keys for the pt_BR layout don't correspond to the codes that the library author provides. For example the code they use for `/` is `0x54` which doesn't correspond with any of the codes shown below. I'll have to do some investigation, thanks for bringing this up. :)
```
      +---+---+---+---+---+---+---+---+---+---+---+---+---+-------+
      |35 |1e |1f |20 |21 |22 |23 |24 |25 |26 |27 |2d |2e |BackSp |
      +---+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-----+
      | Tab |14 |1a |08 |15 |17 |1c |18 |0c |12 |13 |2f |30 | Ret |
      +-----++--++--++--++--++--++--++--++--++--++--++--++--++    |
      |CapsL |04 |16 |07 |09 |0a |0b |0d |0e |0f |33 |34 |31 |    |
      +----+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+---+----+
      |Shi.|32 |1d |1b |06 |19 |05 |11 |10 |36 |37 |38 |  Shift   |
      +----+---++--+-+-+---+---+---+---+---+--++---+---++----+----+
      |Ctrl|Win |Alt |                        |AlGr|Win |Menu|Ctrl|
      +----+----+----+------------------------+----+----+----+----+
```

**Comment by Herna4ndes** [comment]
I don't know if that helps you much. Here in Brazil we usually use the keyboard layout called PT_Br ABNT or PT_Br ABNT2 . 
Thank you very much for your attention. 
![Uploading teclado.png…]()

**Comment by VoidNoi** [comment]
It should work now :) https://github.com/VoidNoi/BadCard/commit/9d40844f57b7d9d626366ee5695880003112e685
I'll be uploading the updated binary soon

**Comment by Herna4ndes** [comment]
Right. I'm looking forward to using the updated version. 

Thank you very much

**Comment by Herna4ndes** [comment]
Are you going to put it in m5burner or just in Github ?

**Comment by VoidNoi** [comment]
It will be in m5burner in a minute or 2. Let me know if everything works when you try it so I can close the issue

**Comment by Herna4ndes** [comment]
As soon as I get home from work I'll test it and get back to you here.

**Comment by Herna4ndes** [comment]
I took the test and it worked. Thank you very much. Any news I come here immediately. hug

**Comment by VoidNoi** [comment]
Great! Closing the issue now :)
